--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#000000"
foreground="#ffffff"
cursor="#f5a2b5"

-- Colors
color0="#4a4b4a"
color1="#d7699a"
color2="#80d468"
color3="#d7a169"
color4="#6985d7"
color5="#c86ad4"
color6="#6fccd1"
color7="#dbdcdc"
color8="#696969"
color9="#d7699a"
color10="#80d468"
color11="#d7a169"
color12="#6985d7"
color13="#c86ad4"
color14="#6fccd1"
color15="#dbdcdc"
