--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1d1f21"
foreground="#c5c8c6"
cursor="#c5c8c6"

-- Colors
color0="#1d1f21"
color1="#CC342B"
color2="#198844"
color3="#FBA922"
color4="#3971ED"
color5="#A36AC7"
color6="#3971ED"
color7="#c5c8c6"
color8="#969896"
color9="#CC342B"
color10="#198844"
color11="#FBA922"
color12="#3971ED"
color13="#A36AC7"
color14="#3971ED"
color15="#ffffff"
