--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1e1e1e"
foreground="#d4d4d4"
cursor="#f44747"

-- Colors
color0="#1e1e1e"
color1="#f44747"
color2="#d7ba7d"
color3="#608b4e"
color4="#569cd6"
color5="#4ec9b0"
color6="#c586c0"
color7="#d4d4d4"
color8="#808080"
color9="#f44747"
color10="#d7ba7d"
color11="#608b4e"
color12="#569cd6"
color13="#4ec9b0"
color14="#c586c0"
color15="#d4d4d4"
