#!/usr/bin/env python
import argparse
import os

def working_dir_make():
    return os.path.join(os.getcwd(), "Makefile")

def get_makefile():
    parser = argparse.ArgumentParser()
    parser.add_argument("--path", help="the path to the Makefile.",
                        type=str,
                        default=working_dir_make())
    args = parser.parse_args()
    return parser, args

def log_makefile_line(line):
    blue = '\x1b[1;34m'
    reset = '\x1b[0m'
    if ": ##" in line:
        command, doc = line.split(": ##")
        print(f"{blue}{command}{reset}: ", end='')
        print(f"{doc.strip()}")

def log_comments(makefile_path):
    with open(makefile_path, 'r') as makefile_text:
        for line in makefile_text:
            log_makefile_line(line)

def main():
    parser, args = get_makefile()
    makefile_path = os.path.abspath(args.path)
    if not os.path.isfile(makefile_path) or not os.path.basename(makefile_path) == "Makefile":
        parser.exit(status=1, message=f"Could not resolve Makefile at {makefile_path}")
    log_comments(makefile_path)

if __name__ == "__main__":
    main()
