#!/bin/sh
VERSION=1.0.0

usage()
{
cat <<EOF
GIG

USAGE
gig <FIELDS>             Quickly create a .gitignore file for the project. 

FLAGS
--help, -h:              Display this help message and exit.
--version, -v:           Display the current version and exit.

EOF
}

if [ -z "$1" ]; then
  printf "Please give fields to gitignore.\n";
  usage;
  exit 1;
fi

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

curl https://www.toptal.com/developers/gitignore/api/"$1" > .gitignore
