#!/bin/sh
VERSION=1.0.0

usage()
{
cat <<EOF
HOTDWM

USAGE
hotdwm             Run dwm in hot reloading mode. 

FLAGS
--help, -h:        Display this help message and exit.
--version, -v:     Display the current version and exit.

EOF
}

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

# shellcheck disable=2015
while type dwm >/dev/null; do dwm && continue || break; done;
