#!/usr/bin/env python3
import argparse
import os

def list_directory(directory_path):
    for filename in os.listdir(directory_path):
        print(os.path.join(directory_path, filename))

def list_file(file_path):
    print(file_path)

def get_path():
    parser = argparse.ArgumentParser()
    parser.add_argument("path", help="The directory or file to list.", type=str)
    args = parser.parse_args()
    return parser, os.path.abspath(args.path)

def main():
    parser, path = get_path()
    if os.path.isfile(path):
        return list_file(path)
    if os.path.isdir(path):
        return list_directory(path)
    parser.exit(status=1, message=f"Could not resolve {path}")

if __name__ == "__main__":
    main()
