#!/usr/bin/env python3
import argparse
import os


def list_directory(directory_path):
    for filename in os.listdir(directory_path):
        full_path = os.path.abspath(os.path.join(directory_path, filename))
        if os.path.isfile(full_path):
            print(full_path)


def main():
    for filename in os.listdir(os.getcwd()):
        if os.path.isdir(filename) and filename[0] != ".":
            list_directory(filename)


if __name__ == "__main__":
    main()
