#!/bin/sh
VERSION=1.0.0

usage()
{
cat <<EOF
VOLUME DECREASE

USAGE
vdec               Decrease the volume by 10%.

FLAGS
--help, -h:        Display this help message and exit.
--version, -v:     Display the current version and exit.

EOF
}

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

pamixer -d 10 --allow-boost
pkill -RTMIN+10 dwmblocks
