#!/bin/sh
VERSION=1.0.0

set -e

usage()
{
cat <<EOF
WATCH

USAGE
w                  Run-watch using the command in .wrc

FLAGS
--help, -h:        Display this help message and exit.
--version, -v:     Display the current version and exit.

EOF
}

if [ ! -f "$PWD"/.wrc ]; then
  printf "%s\n" "Please make a .wrc file with the command to run when files change."
  usage
  exit 1
fi

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac

list-directories-safely | entr -c -r sh "$PWD"/.wrc
