#!/bin/sh
VERSION=1.0.0

usage()
{
cat <<EOF
WEATHER

USAGE
weth               Get a report of the current weather. 

FLAGS
--help, -h:        Display this help message and exit.
--version, -v:     Display the current version and exit.

EOF
}

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    --version|-v)
        printf "%s\n" "$VERSION"
        exit 0
    ;;
    *)
        # Do nothing
        ;;
esac
curl https://wttr.in/Austin\?format\=1\&u
